# Generated by Django 5.1.6 on 2025-03-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantdomain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantDomain',
        ),
    ]
