# Generated by Django 5.1.6 on 2025-05-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_clientsignuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='users_limit',
            field=models.IntegerField(default=3),
        ),
    ]
