# Generated by Django 3.2.6 on 2025-02-18 15:58

import apps.home.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='offer',
            field=models.ForeignKey(default=apps.home.models.Subscription.get_default_offers, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subscriptions', to='home.offer'),
        ),
    ]
