# Generated by Django 5.1.6 on 2025-03-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
