# Generated by Django 5.1.6 on 2025-03-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_subscription_remaining_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي الاشتراك'), ('overdue', 'متأخر في الدفع'), ('suspended', 'مجمّد'), ('banned', 'محظور'), ('new', 'جديد')], default='new', max_length=10),
        ),
    ]
