# Generated by Django 5.1.6 on 2025-05-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
